server:
  port: 8080
  ssl:
    key-store: classpath:mykeystore.p12
    key-store-password: powerlord
    key-store-type: PKCS12
    key-alias: myalias

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
    h2:
      console:
        enabled: true